/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public Integer add(int x, int y) {
        System.out.println("x = " + String.valueOf(x));
        System.out.println("y = " + String.valueOf(y));
        return x + y;
    }
}
