/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(
            classUnderTest.getGreeting(),
            "app should have a greeting"
        );
    }

    @Test
    void test_add() {
        App apptest = new App();
        assertEquals(3, apptest.add(1, 2));
    }
}
